[[redirects]]
from = "/mushroom/saved/:bgcolor/:fgcolor/:shape/"
to = "/.netlify/functions/saved"
status = 200
force = true
_generated_by_eleventy_serverless = "saved"

[[redirects]]
from = "/mushroom/"
to = "/.netlify/functions/mushroom"
status = 200
force = true
_generated_by_eleventy_serverless = "mushroom"

[context.production]
command = "eleventy"

[context.deploy-preview]
command = "npx slinkity"
